repo:
  public: react-client-sdk
  private: react-client-sdk-private

publications:
  - url: https://www.npmjs.com/package/launchdarkly-react-client-sdk
    description: npm

template:
  name: npm

documentation:
  githubPages: true

sdk:
  displayName: "React"
